server:
  port: 8888

opentracing:
  jaeger:
    http-sender:
      #url: http://localhost:14268/api/traces
      url: http://jaeger-collector-demo-kafka.apps.okd.openshifthub.ml/api/traces
    #enable-b3-propagation: true
spring:
  application:
    name: hello-service

logging:
  level:
    io.opentracing: DEBUG
